dotnet/android-tools

src/Xamarin.Android.Tools/Sdks/AndroidSdkWindows.cs
The VS 2017 installer put my NDK in
`C:\ProgramData\Microsoft\AndroidNDK64\android-ndk-r13b`
I think it should check for its location right before checking `C:\`
=> Locate VS 2017 installation of Android NDK

.gitignore, src/Xamarin.Android.Tools.Tests/MonoDroidSdkTests.cs, src/Xamarin.Android.Tools.Tests/Properties/AssemblyInfo.cs, src/Xamarin.Android.Tools.Tests/Xamarin.Android.Tools.Tests.csproj, src/Xamarin.Android.Tools.Tests/packages.config, src/Xamarin.Android.Tools.sln, src/Xamarin.Android.Tools/Sdks/MonoDroidSdkBase.cs, src/Xamarin.Android.Tools/Sdks/MonoDroidSdkWindows.cs
- Included a unit test project with smoke tests (I just used 2.x NUnit). These are passing on my Windows machine with VS 2017.
~~- Uses [vswhere](https://github.com/Microsoft/vswhere) to locate a VS 2017 installation that includes Xamarin. I think this is the preferred method for locating VS 2017 now.~~
- Looks for VS 2017 in known locations
=> Support for finding Xamarin.Android location with only VS 2017 installed

src/Xamarin.Android.Tools.AndroidSdk/AndroidSdk.cs, src/Xamarin.Android.Tools.AndroidSdk/AndroidVersion.cs, src/Xamarin.Android.Tools.AndroidSdk/AndroidVersions.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/MonoDroidSdkBase.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidVersionTests.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidVersionsTests.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/Xamarin.Android.Tools.AndroidSdk-Tests.csproj, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
Commit [xamarin-android/8e7d37bb][xa8e] contains a sign of
duplication: in order to use a `Mono.Android.dll` binding assembly,
not only do we need to *build* the binding assembly, but we *also*
need to update `Xamarin.Android.Build.Utilities.dll`/etc. to "know"
about the new binding version (to map API level to
`$(TargetFrameworkVersion)`).
[xa8e]: https://github.com/xamarin/xamarin-android/commit/8e7d37bb
Even "better" (worse), if the new API level is a *preview*, there is
no *consistent* API level. For example, with API-O, `android.jar`
isn't at:
$(AndroidSdkDirectory)\platforms\android-@API_LEVEL@\android.jar
where `@API_LEVEL@` is 26 (because various codepaths require that the
"api level" be an integer). Instead, it's installed at: …
=> Add AndroidVersions

src/Xamarin.Android.Tools.AndroidSdk/AndroidAppManifest.cs, src/Xamarin.Android.Tools.AndroidSdk/FileUtil.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidAppManifestTests.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/Resources/manifest-simplewidget.xml, src/Xamarin.Android.Tools.AndroidSdk/Tests/Xamarin.Android.Tools.AndroidSdk-Tests.csproj, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
`AndroidAppManifest` allows parsing and modifying select parts of
`AndroidManifest.xml` files which are part of Android projects.
`AndroidAppManifest` is [imported from xamarin-android/8942eca][0].
[0]: https://github.com/xamarin/xamarin-android/blob/8942eca/src/Xamarin.Android.Build.Utilities/AndroidAppManifest.cs
=> Import AndroidAppManifest from xamarin-android/8942eca

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
Fixes https://bugzilla.xamarin.com/show_bug.cgi?id=52928
The order of the default JDK search was in correct. We should be searching
for the latest JDK first since this is what the google tooling needs.
This commit switches the order in which we do the search
=> Can't find JDK 1.8 when building from the command line

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
We were looking for the saved VS SDK entires in the wrong
registry key. VS 2017 passes the registry key via the
`XAMARIN_ANDROID_REGKEY` environment variable.
=> Look for the SDK entries in the correct registry key.

src/Xamarin.Android.Tools.AndroidSdk/AndroidVersions.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidVersionsTests.cs
We have a MaxStableVersion, it is logical that we should
have a MinStableVersion as well.
=> Add MinStableVersion support

src/Xamarin.Android.Tools.AndroidSdk/AndroidSdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/AndroidVersions.cs
The `AndroidVersions.InstalledBindingVersions` property returns all
`AndroidVersion`s for which we have a `Mono.Android.dll` binding
assembly. (*Really*, it's for directories which contain an
`AndroidApiInfo.xml`, which we *assume* to mean that there is a
`Mono.Android.dll` binding assembly.)
This property and an associated
`AndroidSdkInfo.GetInstalledPlatformVersions()` method -- which
returns `AndroidVersion` information for all *installed* API levels
within the Android SDK -- allows the internal `androidtools` repo to
reimplement the `AndroidSdk.GetInstalledPlatformVersions()` and
related methods.
=> Add AndroidVersions.InstalledBindingVersions property

src/Xamarin.Android.Tools.AndroidSdk/AndroidSdkInfo.cs
Commit f13889c0 added `AndroidSdkInfo.SetPreferredAndroidNdkPath()`,
`AndroidSdkInfo.SetPreferredAndroidSdkPath()`, and
`AndroidSdkInfo.SetPreferredJavaSdkPath()`.
The problem is, these methods are not usable in all scenarios.
The purpose of these methods is to allow e.g. the IDE to allow the
developer to alter the preferred Android NDK, SDK, or JDK paths.
Implicit in this purpose is that the *existing* paths may be invalid.
Thus, if we assume that there is no Android SDK or JDK known by
`AndroidSdkInfo`, but "someone" knows of one and wants to use that in
the future, the obvious thing to do would be to call e.g.
`AndroidSdkInfo.SetPreferredAndroidSdkPath()`.
Therein lines the problem: these are *instance* methods, and the
`AndroidSdkInfo` constructor *requires* that *all* paths be valid, …
=> Allow AndroidSdkInfo.SetPreferred*Path() to work

src/Xamarin.Android.Tools.AndroidSdk/AndroidVersions.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidVersionsTests.cs
Context: https://github.com/xamarin/androidtools/pull/87
Commit aad97f16 assumed that "OS Version" and "Framework Version" were
two related yet distinct constructs, such that e.g.
`AndroidVersions.GetIdFromFrameworkVersion()` only needed to worry
about "Framework Versions".
There was no functionality to look up *anything* by "OS Version",
though such a thing could now be cobbled together via LINQ,
`AndroidVersions.InstalledBindingVersions`, and
`AndroidVersion.OSVersion`.
Unfortunately, when it came time to update `androidtools` to use
`xamarin-android-tools` (this repo), that overlooked assumption reared
its head, cause many unit tests to fail *because* there was an
underlying need to lookup API levels/IDs/etc. via OS Version.
This leaves a choice:
1. "Unify" OS Version and Framework …
=> OSVersion is an alias for Framework Version

.gitignore, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
In cases where `AndroidSdkInfo` is used outside of Visual Studio, such
as Embeddinator-4000, a new fallback path for the Android SDK is needed
on Windows.
At some point in the past, Visual Studio (or Xamarin) Installer
installed to:
C:\Program Files (x86)\Android\android-sdk-windows
Now it is installed to (VS 2017):
C:\Program Files (x86)\Android\android-sdk
Helps fix https://github.com/mono/Embeddinator-4000/issues/599 
Changes:
- Added another fallback path for the Android SDK, mirrored what I did
in the past for VS 2017 and the Android NDK
- Added .vs/ to the .gitignore for Windows developers
=> [windows] fallback path for Android SDK

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
During the implementation of the new xamarin-android-tools we lost the changes in [1]. These are needed on windows to make sure we are using legacy install locations of the SDK/NDK if they exist.
[1] https://github.com/xamarin/androidtools/pull/57
=> Add back in missing defaut Paths for GetAllAvailableAndroidNdks and GetAllAvailableAndroidSdks

src/Xamarin.Android.Tools.AndroidSdk/AndroidSdkInfo.cs
It is needed to allow user to select between existing/new SDK locations
=> Expose AllAndroidSdks as VS4Mac Installer depends on it

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs
We missed some old hardcoded paths for MacOS. This PR adds them back.
=> Add Missing code to check old paths

src/Xamarin.Android.Tools.AndroidSdk/AndroidVersions.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidVersionsTests.cs
We had a bug on our logic to calculate the `MaxStableVersion`.
The first time through the `LoadVersions` method `MaxStableVersion`
would ALWAYS be `null`. As a result regardless of whether the
first version was stable or not it would be assigned to the
property. This would then cause build failures later down the
build process because we were using an unstable api.
So the fix it to completely ignore unstable apis. This way the
first STABLE api we find will be the first value we assign.
=> [Xamarin.Android.Tools.AndroidSdk] Unstable framework versions are used

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/597752
Whenever (for whatever reason) user runs the Visual Studio for Mac installer as
root using `sudo`, ownership of the `~/.config/xbuild` directory as well as the
configuration file created inside it will be set to root:root. This is due to a
couple of facts:
* `sudo` (without parameters) switches the user but doesn't reset the
environment variables. In effect the `$HOME` variable will point to home
directory of the user running `sudo`, not root
* Mono's `Environment.GetFolderPath` uses `$HOME` to find the location of
the user's home directory.
The outcome of the above is that if Xamarin.Android.Tools create the directory
and the config file from scratch, their ownership is going to be incorrect and
that causes the Visual …
=> Fix ~/.config/xbuild/* ownership on creation when under sudo

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
On Windows, as part of VisualStudio installer, we can install the Microsoft OpenJdk version.
This jdk has priority when we select the default for the user.
=> Set OpenJdk path as default if it is available on windows

src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/OS.cs, src/Xamarin.Android.Tools.AndroidSdk/ProcessUtils.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/JdkInfoTests.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/Xamarin.Android.Tools.AndroidSdk-Tests.csproj, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
Context: https://github.com/xamarin/xamarin-android-tools/pull/29#issuecomment-400048306
Refactor out the [underlying functionality][0] of the
[`<JdkInfo/>` task][1] so that it is more easily usable.
[0]: https://github.com/xamarin/java.interop/commit/4bd9297f311b3e0fb3e07335507a38278b83d255
[1]: https://github.com/xamarin/java.interop/blob/master/src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/JdkInfo.cs
=> [Xamarin.Android.Tools.AndroidSdk] Add JdkInfo

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs
Use JdkInfo to get the Java SDK path, and fix Java SDK validation to work with OpenJDK.
Fixes VSTS #652760 and VSTS #646086
=> [Mac] Use the new JdkInfo to fetch the Java SDK path and fix validation

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidSdkInfoTests.cs
Context: https://github.com/xamarin/xamarin-android/pull/2004
Context: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3656/testReport/junit/Xamarin.Android.Build.Tests/ResolveSdksTaskTests/ResolveSdkTiming___Debug/
Before commit 75530565, the only validation performed on the
`AndroidSdkInfo`'s `javaSdkPath` parameter was "does
`{javaSdkPath}/bin/jarsigner` exist?
This is the world the [xamarin-android unit tests assumed][0], as it
would create `{javaSdkPath}/bin/jarsigner` and
`{javaSdkPath}/bin/javac.bash` (among others), but *not*
`{javaSdkPath/bin/javac`.
Then came commit 75530565, which altered
`AndroidSdkUnix.ValidateJavaSdkLocation()` semantics so that it now
*required* the presence of `{javaSdkPath}/bin/javac`.
This changed caused the xamarin-android unit tests to …
=> [Xamarin.Android.Tools.AndroidSdk] Revert JDK validation

src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidSdkInfoTests.cs
Improve the `AndroidSdkInfoTests.Constructor_Paths()` test to remove
the temporary Android SDK & JDK directories that it creates.
=> [tests] Remove temporary directories

src/Xamarin.Android.Tools.AndroidSdk/AndroidSdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidSdkInfoTests.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/JdkInfoTests.cs
Context: https://paper.dropbox.com/doc/OpenJDK-and-You--AH1yWKdVXgno~uXYfmcUAZTwAg-NoECAe2XkBQeoxFfGL6ea
Add `AndroidSdkInfo.DetectAndSetPreferredJavaSdkPathToLatest()`.
=> Add AndroidSdkInfo.DetectAndSetPreferredJavaSdkPathToLatest()

src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidSdkInfoTests.cs
The test backs up monodroid-config.xml, but when it tries to move the
backup to its original place it fails because the version created during
the test is in its place.
=> Fix test DetectAndSetPreferredJavaSdkPathToLatest

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs
Context: https://github.com/xamarin/androidtools/pull/119
Context: https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build?buildId=1908630
Context: https://github.com/xamarin/androidtools/pull/120
Context: https://devdiv.visualstudio.com/DevDiv/DevDiv%20Team/_build?buildId=1908776
How does `AndroidSdkInfo` determine the appropriate value to return
from `AndroidSdkInfo.AndroidNdkPath`?
Firstly, it checks `$HOME/.config/xbuild/monodroid-config.xml`.
If that file doesn't exist, or it doesn't contain a
`/monodroid/android-ndk/@path` attribute value, then `AndroidSdkInfo`
checks `$PATH`, and attempts to find `ndk-stack`.  If `ndk-stack` can
be found in `$PATH`, the containing directory is used:
$ mv $HOME/.config/xbuild/monodroid-config.xml{,.none}
$ PATH=/path/to/my/ndk:$PATH csharp …
=> Allow finding NDK location based on $PATH

src/Xamarin.Android.Tools.AndroidSdk/AndroidSdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidSdkInfoTests.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/JdkInfoTests.cs
Commit 511d580b didn't provide unit tests to ensure that the
Android NDK could be found based on probing `$PATH` for `ndk-stack`.
Update `AndroidSdkInfoTests` to ensure that the NDK to be found based
on `$PATH`, as well as the Android SDK and JDK.
Additionally, JDK-via-$PATH detection hit a few hiccups:
1. `JdkInfo.GetKnownSystemJdkInfos()` would always check
`/usr/libexec/java_home` before `$PATH`, meaning it wasn't
possible to test JDK-via-$PATH!
Alter the ordering of `JdkInfo.GetKnownSystemJdkInfos()` so that
we probe `$PATH` before hitting `/usr/libexec/java_home`.
2. `JdkInfo` requires that the `java.home` property be printed, which
`JdkInfoTests.CreateFauxJdk()` didn't print, which caused the fake
JDK to be skipped.  Fix `JdkInfoTests.CreateFauxJdk()` so that the
resulting `java` is …
=> [tests] Unit tests for finding NDK location based on $PATH

src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/JdkInfoTests.cs
Fixes: https://github.com/xamarin/xamarin-android-tools/issues/39
The `release` file contained within the
[Microsoft OpenJDK Distribution Preview][0] contains an entry which
broke the `release` parser within `JdkInfo`, an entry which doesn't
contain double quotes around the value:
BUILD_NUMBER=9
This causes an exception to be thrown when `JdkInfo` attempts to parse
the `release` file:
System.ArgumentOutOfRangeException : Length cannot be less than zero.
Parameter name: length
at System.String.Substring (System.Int32 startIndex, System.Int32 length) [0x0004a] in <7e59c4ad7b424f9eab0db1b78ec1804f>:0
at Xamarin.Android.Tools.JdkInfo.GetReleaseProperties () [0x0006b] in <3975ab851981476abded14492926b261>:0
at Xamarin.Android.Tools.JdkInfo..ctor (System.String homePath) [0x00159] in …
=> Don't require quotes around `release` values

src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
Context: https://github.com/xamarin/xamarin-android/pull/2004#issuecomment-410243364
There are a two (related) "usability" issues with
`JdkInfo.GetKnownSystemJdkInfos()`:
1. It returns duplicate paths, and
2. There's no way of knowing where a path "came from"
For example:
$ csharp -r:bin/Debug/Xamarin.Android.Tools.AndroidSdk.dll
csharp> using Xamarin.Android.Tools;
csharp> JdkInfo.GetKnownSystemJdkInfos();
{
JdkInfo(Version=1.8.0.77, Vendor="Oracle Corporation", HomePath="/Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home"),
Not a valid JDK directory: `/Library/Java/JavaVirtualMachines/1.6.0_65-b14-462.jdk/Contents/Home`
System.ArgumentException: Could not find required file `jvm` within `/Library/Java/JavaVirtualMachines/1.6.0_65-b14-462.jdk/Contents/Home`; is this a valid …
=> Allow an optional locator to be provided to JdkInfo

src/Xamarin.Android.Tools.AndroidSdk/AndroidSdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidSdkInfoTests.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/JdkInfoTests.cs
Fixes: http://work.devdiv.io/661401
The version numbers which the Microsoft OpenJDK packages provide was
not consistent with what `JdkInfo` expected: the `release` file would
have a `JAVA_VERSION` value which was a three-tuple, and didn't
include the `BUILD_NUMBER` value.  For example:
JAVA_VERSION="1.8.0"
BUILD_NUMBER=7
Unfortunately, `JdkInfo.GetJavaVersion()` was only taking
`JAVA_VERSION` into consideration, so when multiple different OpenJDK
packages were processed which all had the *same* `JAVA_VERSION` value
but *different* `BUILD_NUMBER` values,
`JdkInfo.GetMacOSMicrosoftJdks()` returned the "wrong" one first.
(In actuality, the one it returned first was not knowable, and was
probably whatever `Directory.EnumerateDirectories()` returned first.)
Simple enough, we just need to take …
=> Take BUILD_NUMBER into consideration for Version sorting

src/Xamarin.Android.Tools.AndroidSdk/AndroidSdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/ProcessUtils.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidSdkInfoTests.cs
What happens if there is no JDK installed on macOS?
$ mv ~/Library/Developer/Xamarin/jdk ~/Library/Developer/Xamarin/jdk.bk
$ sudo mv /Library/Java/JavaVirtualMachines /Library/Java/JavaVirtualMachines.bk
`JdkInfo` doesn't like this, which is to be expected, but *how* it
doesn't like it is...bad:
$ csharp -r:bin/Debug/Xamarin.Android.Tools.AndroidSdk.dll
csharp> Xamarin.Android.Tools.JdkInfo.GetKnownSystemJdkInfos();
Error getting SDK info:
System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
at System.Xml.XmlTextReaderImpl.Throw (System.Exception e)
at System.Xml.XmlTextReaderImpl.Throw (System.String res, System.String arg)
at System.Xml.XmlTextReaderImpl.Throw (System.String res)
at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace ()
at …
=> Better support no installed JDKs on macOS

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
We are migrating the signing of this repository to occur in CI via MicroBuild. Other projects have this as their dependency and to make sure that they are correctly signed, we need to push this through.
This should have *no* impact on local builds, other than downloading a new public .nupkg.
=> Add MicroBuild reference + Sign target

src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs
This checks for /System/Library/Java/JavaVirtualMachines if we're
trying to use the system java. If there is no system Java installed
then calling /usr/bin/java has the unfortunate effect of popping up
a dialog telling the user to install a JDK.
Fixes VSTS #735545
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/735545
=> Check if system Java is installed

src/Xamarin.Android.Tools.AndroidSdk/AndroidVersions.cs
KnownVersions should be the only place we modify when new versions are
published. AndroidVersions right now provides information on what's
installed and what's supported, but not what exists. For Android
Manifest we also need to know what exists because Minimum Android
Version and Target may be anything (regardless of what the compile
version is). This is related to:
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/777180
=> Made KnownVersions public

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidSdkInfoTests.cs
A few versions ago, the ndk started shipping inside the sdk path. In VS
we are now checking this directories, and only using the registry keys
as fallbacks (meaning, if the ndk exists in the sdk it takes priority
over anything else). According to our telemetry, 100% of the users are
using the ndk this way. This commit adds that check so we can have
parity between what Android does and what VS does. Also, it serves as
preparation for VS removing that option (meaning, it will not be
configurable and _always_ work in the way described in this commit).
=> Added ndk-bundle directories to ndk search in Windows

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs
Fixes VSTS #826178
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/826178
=> Check if the path exists before trying to enumerate it.

src/Xamarin.Android.Tools.AndroidSdk/Tests/Xamarin.Android.Tools.AndroidSdk-Tests.csproj, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
This makes it fully compatible with NS2. Otherwise, an SDK targeting pack needs to be installed and 
a whole bunch of facade assemblies are included as part of the build which aren't needed and can 
cause issues when running inside the IDE.
=> Code that runs in VS needs to target either net46 or net472 in dev16+

src/Xamarin.Android.Tools.AndroidSdk/Tests/Xamarin.Android.Tools.AndroidSdk-Tests.csproj, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
Under VS2017+, code must either target net46 or net472 and nothing in between.
Otherwise, run-time errors might happen if the wrong assemblies (facades for NS2 support)
are inadvertently bound at compile time and loaded at run-time.
(d16-2 backport)
=> Downgrade to net46 for compatibility with VS2017+

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs, src/Xamarin.Android.Tools.AndroidSdk/Tests/AndroidSdkInfoTests.cs
Fixes: http://feedback.devdiv.io/606218
Something has happened with Xamarin.Android builds running on Azure
DevOps recently, builds are now failing with:
ResolveSdks
...
Errors
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(721,2): error XA5300: The Java SDK Directory could not be found. Please set via /p:JavaSdkDirectory. [d:\a\1\s\Xamarin.Android.Lite\Xamarin.Android.Lite.csproj]
Azure DevOps has posted a "workaround" document:
https://github.com/microsoft/azure-pipelines-image-generation/blob/1371aa8548aa135c3be783bd854681118ca10f78/images/win/Vs2019-Server2019-Readme.md#known-issues
It suggests adding this property to MSBuild calls:
/p:JavaSdkDirectory="$(JAVA_HOME_8_X64)"
Reviewing a user's build log from …
=> [Windows] check %JAVA_HOME% for locating Jdk

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
- fixes bug 938504: AndroidSdk initialization fails with a System.ArgumentNullException when no AndroidSdk is detected on the user machine
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/938504
=> Avoids NRE trying to get the list of available NDK if the AndroidSdk path is null

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
@DmitriyKirakosyan ran into a build failure when attempting to bump
xamarin/android-sdk-installer to use commit bfb66f38:
external\androidtools\external\xamarin-android-tools\src\Xamarin.Android.Tools.AndroidSdk\Xamarin.Android.Tools.AndroidSdk.csproj(0,0):
Error MSB4057: The target "BuiltProjectOutputGroupDependencies" does not exist in the project.
[Further investigation][0] showed that the MSB4057 occurs because
`Xamarin.Android.Tools.AndroidSdk.csproj` uses the `$(TargetFrameworks)`
property (plural), and to avoid the MSB4057 the `$(TargetFramework)`
property (singular) should instead be used.
As `Xamarin.Android.Tools.AndroidSdk.csproj` also targets
.NET Standard 2.0, and [.NET Standard 2.0 supports .NET 4.6][1],
we can fix the MSB4057 by dropping the build of `net461`.
[0]: …
=> [Xamarin.Android.Tools.AndroidSdk] Remove net461

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
In https://developercommunity.visualstudio.com/content/problem/883179/ilegal-characters-in-path-after-fresh-install.html, the user is hitting an exception when checking for an executable from paths found in their registry.
If we hit an error we should just return `false` as there obviously isn't a valid install located there.
=> [AndroidSdkWindows] Guard against exception checking registry.

src/Xamarin.Android.Tools.AndroidSdk/AndroidSdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidSdkInfoTests.cs
Google replaced 'tools' with 'cmdline-tools'
Android sdk now supports multiple 'cmdline-tools' versions installed SxS
For the sake of simplicity, using latest installed version for now.
Since new 'cmdline-tools' doesnt contain Emulator executable, replaced the searching path with `Path.Combine (AndroidSdkPath, "emulator")`
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1109288
=> Add support for new 'cmdline-tools'

Makefile, NuGet.config, src/Xamarin.Android.Tools.AndroidSdk/AndroidSdkInfo.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidSdkInfoTests.cs
Context: https://github.com/xamarin/xamarin-android/pull/4735 >
https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3771781&view=ms.vss-test-web.build-test-results-tab&runId=13535824&resultId=100072&paneView=attachments
Context: https://github.com/xamarin/xamarin-android/pull/4567
Context: https://github.com/xamarin/androidtools/commit/a3965baeea566ba6a1f346c676d9e2d5ecba6167
The Windows Smoke Tests are failing on PR #4735, because the wrong
Android SDK Build-tools version is being used:
Task "ResolveAndroidTooling" (TaskId:9)
Task Parameter:AndroidSdkBuildToolsVersion=29.0.2 (TaskId:9)
…
Trying build-tools path: C:\Users\dlab14\android-toolchain\sdk\build-tools\30.0.0-rc4 (TaskId:9)
…
ResolveAndroidTooling Outputs: (TaskId:9)
AndroidSdkBuildToolsPath: …
=> [Xamarin.Android.Tools.AndroidSdk] Preview Build-Tools are Last

src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidSdkInfoTests.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/JdkInfoTests.cs
Context: https://github.com/xamarin/xamarin-android/pull/4567
`JdkInfo.GetKnownSystemJdkInfos()` returns a list of "known JDK
locations", and the order of the returned paths was, basically,
"locations that Xamarin/Microsoft controls come first."
`AndroidSdkWindows.GetJdkInfos()` reads the Windows registry and is
"controlled by" Visual Studio (unless someone is editing the Registry
by hand…).  If not on Windows, `GetConfiguredJdks()` reads
`monodroid-config.xml` (managed by Visual Studio for Mac); failing
that we probe some "well known Microsoft-controlled" directory
locations…
…and only failing *that* do we try the `$JAVA_HOME` environment
variable, the ["de-facto" way][0] to tell software where Java is
installed, and if `$JAVA_HOME` isn't set we further fallback to
checking directories …
=> [Xamarin.Android.Tools.AndroidSdk] Prefer JAVA_HOME

src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
Context: https://github.com/xamarin/xamarin-android/pull/4567
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3781637&view=logs&j=aacb7678-d5ef-5d73-dd2c-3def32e966f3&t=36563657-e889-567e-4d1d-090ca934735a
We're trying to get our CI to use JDK11 (xamarin/xamarin-android#4567),
for which we added support for a `JI_JAVA_HOME` environment variable
"override"; see 13cc497a.
However, even with `JI_JAVA_HOME` set, `nuget restore` still fails:
…\Xamarin.Android.Tooling.targets(65,5): warning XA5300: Not a valid JDK directory: `C:\Users\dlab14\android-toolchain\jdk`; via locator: $JI_JAVA_HOME
The question is *why* it's an invalid JDK directory.  (It certainly
looks like it should be valid!)
While we *do* print out the contents of `e.ToString()`, this is only
written as …
=> [Xamarin.Android.Tools.AndroidSdk] Improve utility of JDK warnings

src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs
Context: https://github.com/xamarin/xamarin-android/pull/4567
Commit 36d7fee5 added support for JetBrains OpenJDK 11 detection on
macOS and Linux.
Lacking was *Windows* support for JetBrains OpenJDK 11, because of
course it has to be different.
In particular, OpenJDK 11 *moves the `jvm` library* for Windows.
We checked for it in `{HomePath}\jre\**\jvm.dll` or
`{HomePath}\lib\**\jvm.dll`, but neither of those exist.  Instead,
OpenJDK 11 has `jvm.dll` in `{HomePath}\bin\server\jvm.dll`, which is
also the only `.dll` file in the `.tar.gz` which exports the symbol
`JNI_CreateJavaVM`.
Update `JdkInfo` so that it looks for `{HomePath}\bin\server\jvm.dll`
to populate `JdkInfo.JdkJvmPath`.
=> [Xamarin.Android.Tools.AndroidSdk] JdkInfo + JDK11 + Windows

src/Xamarin.Android.Tools.AndroidSdk/AndroidVersions.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidVersionsTests.cs
In .NET 5, there is a single `AndroidApiInfo.xml` file:
<AndroidApiInfo>
<Id>30</Id>
<Level>30</Level>
<Name>R</Name>
<Version>v11.0</Version>
<Stable>True</Stable>
</AndroidApiInfo>
And so if you call `AndroidVersions.GetApiLevelFromId(29)` you would
always get `null` returned. This is because `KnownVersions` does not
have API 29 or 30 listed.
To fix this and *not* update `KnownVersions`, we can make the various
`GetApiLevelFromId` methods return the incoming API level as a last
resort.
So if 29 comes in, 29 can be returned and assumed to be a valid API
level.
=> Return a default for unknown API levels

azure-pipelines.yaml
Context: https://docs.microsoft.com/azure/devops/pipelines/tasks/test/publish-test-results#yaml-snippet
Context: https://dev.azure.com/xamarin/public/_build/results?buildId=21614&view=ms.vss-test-web.build-test-results-tab
Currently, if a test fails on macOS the build will still be green.
We need to set `failTaskOnFailedTests` on the `PublishTestResults` step.
I also filled out `testRunTitle`, to fix the display name shown on
test results.
=> [build] fail macOS build if tests fail

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.Versions.props
This commit is part of an effort to make sure all of our tooling uses
the same android sdk versions. It adds a MSbuild `.props` file
which contains the versions of parts of the Android Sdk. It is
these versions which will be installed/used by default when a
user first installs the product, or if they do not specify
other versions in their `csproj`.
If the new file is changed ALL repos referencing this one
will need to be updated. This includes all repos which pull
in this one via `androidtools`.
=> Add a .props file which contains the Android SDK Tools versions.

src/Xamarin.Android.Tools.AndroidSdk/AndroidVersions.cs
Context: https://github.com/xamarin/xamarin-android/pull/4873
Although this is related to https://github.com/xamarin/xamarin-android/pull/4873, it is not the full fix. We probably should list the missing versions here anyway, though.
=> Add API 29 and 30 to KnownVersions

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidSdkInfoTests.cs
Context: https://build.azdo.io/xamarin/public/21545
An environment change on Azure DevOps seems to cause the test failure
on Windows:
Ndk_PathInSdk
AndroidNdkPath not found inside sdk!
Expected string length 71 but was 53. Strings differ at index 3.
Expected: "C:\Users\VssAdministrator\AppData\Local\Temp\tmpAE78.tmp\sdk\..."
But was: "C:\Program Files (x86)\Android\android-sdk\ndk-bundle"
It appears that `xamarin-android-tools` is preferring an `ndk-bundle
found on the system instead of the value passed in for
`AndroidSdkPath`.
To make matters worse, use of `Distinct()` returns an unordered
sequence, and so the sort ordering is unknown:
https://docs.microsoft.com/dotnet/api/system.linq.enumerable.distinct
To fix this, let's not use `ToList()` or add `AndroidSdkPath` to the
list at all. We …
=> Fix sort ordering for ndk-bundle, add macOS support

src/Xamarin.Android.Tools.AndroidSdk/AndroidVersions.cs, src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs
Fixes a few NRT warnings in `JdkInfoVersionComparer`.
There are also some NRT warnings in `EqualityComparer<T>`, but this class is `private` and not used anywhere, so we're removing it instead.
=> [XAT.AndroidSdk] Fix a few nullability warnings.

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.Versions.props
We were late in attempting to update dependencies, resulting in an
"undesirable" first run experience on macOS+Visual Studio for Mac, in
which creating a new Xamarin.Forms project would elicit a dialog to
the user:
> **Android SDK components needed**
>
> The project … requires the following Android SDK
> components that are not currently installed:
>
> -- Android SDK Platform 28 v6
>
> The download will take a few minutes…
>
> [Cancel] [Download and Install]
…because the default template would be using Xamarin.Android
`$(TargetFrameworkVersion)`=v9.0 (API-28), which wasn't installed.
"Revert" MSBuild properties so that API-28 -related packages are
referenced, which will allow them to be installed on macOS, which will
thus prevent the above dialog from being shown:
* …
=> [Xamarin.Android.Tools.AndroidSdk] Prefer API-28 Component Versions

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.Versions.props
Context: https://dl-ssl.google.com/android/repository/repository2-1.xml
Update the preferred Android SDK component versions to the current latest
versions listed in the [Android Repository file][0]:
* `$(AndroidSdkBuildToolsVersion)`/build-tools to 30.0.2
* `$(AndroidCommandLineToolsVersion)`/cmdline-tools to 2.1
* `$(AndroidSdkPlatformToolsVersion)`/platform-tools to 30.0.4
* `$(AndroidSdkPlatformVersion)`/platform to android-30
* `$(AndroidNdkVersion)`/NDK to 21.3.6528147
[0]: https://dl-ssl.google.com/android/repository/repository2-1.xml
=> [Xamarin.Android.Tools.AndroidSdk] Update SDK component for API-30

.gitignore, .vscode/extensions.json, .vscode/settings.json, .vscode/tasks.json, Directory.Build.props, Makefile, NuGet.config, README.md, azure-pipelines.yaml, tests/Xamarin.Android.Tools.AndroidSdk-Tests/Xamarin.Android.Tools.AndroidSdk-Tests.csproj
Updates `Xamarin.Android.Tools.AndroidSdk-Tests.csproj` to target only
`netcoreapp3.1`, and updates all test running logic to use dotnet test.
This will allow us to remove the `globalPackagesFolder` override from
NuGet.config as NUnit.ConsoleRunner is no longer referenced or used.
The YAML pipeline has also been consolidated a bit to reduce step
duplication.  A matrix strategy is now used to run the same steps in
parallel on both macOS and Windows.  OS-specific steps are now hidden
behind a condition so that we don't duplicate artifact uploading and
publishing.
=> [tests] Use dotnet test to run AndroidSdk-Tests

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidSdkInfoTests.cs
Context: https://github.com/xamarin/xamarin-android/issues/5499
Context: https://github.com/xamarin/xamarin-android/issues/5526
Context: https://github.com/android/ndk/issues/1427
Context: https://developer.android.com/studio/command-line/variables#envar
Xamarin.Android is not (yet) compatible with the recently released
Android NDK r22 version.  Azure build images have recently rolled out an
update which includes NDK r22 and, thus, it breaks builds for customers
using any form of Xamarin.Android AOT build.
In attempt to detect broken/incompatible NDK versions as well as select
the "best one", this commit adds code to scan the known NDK locations in
search of the preferred version.  The search is conducted as follows:
1. If the user selected a preferred NDK location, it is always used.
2. …
=> [NDK] Locate and select only compatible NDK versions

NuGet.config, azure-pipelines.yaml
Context: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610
Context: https://azure.microsoft.com/en-us/resources/3-ways-to-mitigate-risk-using-private-package-feeds/
Context: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/12676/ncident-help-for-Substitution-attack-risk-from-multiple-package-feeds
There is a Package Substitution Attack inherent in NuGet, whereby
if multiple package sources provide packages with the same name,
it is *indeterminate* which package source will provide the package.
For example, consider the [`XliffTasks` package][0], currently
provided from the [`dotnet-eng`][1] feed, and *not* present in the
NuGet.org feed.  If a "hostile attacker" submits an `XliffTasks`
package to NuGet.org, then we don't know, and cannot control, whether
the …
=> [ci] Update packageSources in NuGet.config

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidSdkInfoTests.cs
@PureWeen was hitting a problem building a .NET 6 app on macOS:
Task "ResolveSdks"
...
at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
at System.IO.Enumeration.FileSystemEnumerator`1.Init()
at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
at …
=> [macOS] fix DirectoryNotFoundException on clean systems

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Changes: https://github.com/xamarin/LibZipSharp/compare/1.0.23...1.0.24
* xamarin/LibZipSharp@86f8ae57: Bump to 1.0.24
* xamarin/LibZipSharp@582eb2c1: Include the Pdb when using 'LibZipSharpBundleAllNativeLibraries'
=> Bump to xamarin/LibZipSharp/main@86f8ae57 [1.0.24]

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs
In #103 this line was added:
```
string ev = Environment.GetEnvironmentVariable (envVar);
```
With NRT, `Environment.GetEnvironmentVariable` returns `string?` instead of `string`, causing the warning:
```
Warning CS8600: Converting null literal or possible null value to non-nullable type.
```
We can avoid it by using `var` instead of `string`.
=> Fix Warning CS8600: Converting null literal or possible null value to non-nullable type.

src/Xamarin.Android.Tools.AndroidSdk/ProcessUtils.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidSdkInfoTests.cs
Fixes: https://developercommunity.visualstudio.com/t/illegal-character-exception-in-xamarinandroid-afte/1363149
In 16.9 we are getting some reports of:
(_ResolveSdks target) ->
error XARSD7004: System.ArgumentException: Illegal characters in path.
error XARSD7004:    at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
error XARSD7004:    at System.IO.Path.Combine(String path1, String path2)
error XARSD7004:    at Xamarin.Android.Tools.ProcessUtils.<FindExecutablesInDirectory>d__9.MoveNext() in /Users/builder/azdo/_work/278/s/xamarin-android/external/xamarin-android-tools/src/Xamarin.Android.Tools.AndroidSdk/ProcessUtils.cs:line 177
error XARSD7004:    at Xamarin.Android.Tools.ProcessUtils.<FindExecutablesInPath>d__8.MoveNext() in …
=> Fix for invalid values in %PATH% or %PATHEXT%

Xamarin.Android.Tools.sln, src/Xamarin.Android.Tools.AndroidSdk/AndroidSdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Jdks/AzulJdkLocations.cs, src/Xamarin.Android.Tools.AndroidSdk/Jdks/JdkLocations.MacOS.cs, src/Xamarin.Android.Tools.AndroidSdk/Jdks/JdkLocations.Windows.cs, src/Xamarin.Android.Tools.AndroidSdk/Jdks/JdkLocations.cs, src/Xamarin.Android.Tools.AndroidSdk/Jdks/MicrosoftOpenJdkLocations.cs, src/Xamarin.Android.Tools.AndroidSdk/Jdks/OracleJdkLocations.cs, src/Xamarin.Android.Tools.AndroidSdk/Jdks/VSAndroidJdkLocations.cs, src/Xamarin.Android.Tools.AndroidSdk/Jdks/XAPrepareJdkLocations.cs, src/Xamarin.Android.Tools.AndroidSdk/OS.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidSdkWindowsTests.cs, tools/ls-jdks/App.cs, tools/ls-jdks/ls-jdks.csproj
Context: https://www.azul.com/downloads/zulu-community/
Commit 237642ce removed support for the ancient
`microsoft_dist_openjdk_*` versions, replacing it with the newer
[Microsoft OpenJDK][0].
One problem with this change is one of *compatibility*:
`microsoft_dist_openjdk_` was a build of JDK 1.8, while
Microsoft OpenJDK only provides builds for JDK 11 and later.
This is a problem, as the [Visual Studio Android Designer][1]
currently requires JDK 1.8, and is not yet compatible with JDK 11.
Add support to probe for for [Azul Zulu OpenJDK][2] installation
directories, as Zulu provides updated JDK 1.8 installers.
Additionally, refactor and centralize the JDK Location logic.
Previously, `JdkInfo.GetKnownSystemJdkInfos()` would return all of
the Windows installation locations before the …
=> [Xamarin.Android.Tools.AndroidSdk] Probe for Zulu JDK

src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Jdks/AdoptOpenJdkLocations.cs
Context: https://adoptopenjdk.net
Add support to probe for the [AdoptOpenJDK][0] installation
directories.
[0]: https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot
=> [Xamarin.Android.Tools.AndroidSdk] Probe for AdoptOpenJDK Locations

src/Xamarin.Android.Tools.AndroidSdk/Jdks/JdkLocations.Windows.cs
Fix CS0168 warning in `JdkLocations.Windows.cs`:
Jdks/JdkLocations.Windows.cs(42,24): warning CS0168: The variable 'e' is declared but never used
=> [Xamarin.Android.Tools.AndroidSdk] Fix CS0168 warning

src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Jdks/MicrosoftDistJdkLocations.cs
Partially reverts commit 237642ce.
The plan to remove support for the obsolete `microsoft_dist_openjdk_`
JDK distribution has hit a few "snags", and thus we cannot remove
support for the legacy `microsoft_dist_openjdk_` package as quickly
as we had hoped.
Re-introduce support for the `microsoft_dist_openjdk_` JDK
installation location.
=> [Xamarin.Android.Tools.AndroidSdk] Support Microsoft Disk JDK

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
I've been hitting errors running tests locally on Windows after building
with .NET 6 Preview 3:
Error Message:
System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Stack Trace:
at Xamarin.ProjectTools.DotNetXamarinProject.SaveProject()
at Xamarin.ProjectTools.XamarinProject.Save(Boolean saveProject) in C:\Users\Peter\source\xamarin-android\src\Xamarin.Android.Build.Tasks\Tests\Xamarin.ProjectTools\Common\XamarinProject.cs:line 241
at Xamarin.ProjectTools.ProjectBuilder.Save(XamarinProject project, Boolean doNotCleanupOnUpdate, Boolean saveProject) in C:\Users\Peter\source\xamarin-android\src\Xamarin.Android.Build.Tasks\Tests\Xamarin.ProjectTools\Commo …
=> [Microsoft.Android.Build] Use MSBuild NuGets

src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Properties/Resources.Designer.cs, src/Xamarin.Android.Tools.AndroidSdk/Properties/Resources.resx, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.cs.xlf, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.de.xlf, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.es.xlf, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.fr.xlf, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.it.xlf, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.ja.xlf, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.ko.xlf, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.pl.xlf, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.pt-BR.xlf, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.ru.xlf, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.tr.xlf, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.zh-Hans.xlf, src/Xamarin.Android.Tools.AndroidSdk/Properties/xlf/Resources.zh-Hant.xlf
Context: https://dev.azure.com/xamarin/public/_build/results?buildId=40929&view=logs&j=cfef19e4-4225-5e84-636a-86ba2231ac21&t=cd3bc6c3-ac29-5320-67c9-5fb59fc8e05c&l=732
dotnet/maui has hit some build failures such as:
error XARSD7000: System.Xml.XmlException: Root element is missing.
error XARSD7000:   at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x00027] in <cd2a19182af54ce694ec155c18cdf0fc>:0
error XARSD7000:   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <cd2a19182af54ce694ec155c18cdf0fc>:0
error XARSD7000:   at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0035d] in <cd2a19182af54ce694ec155c18cdf0fc>:0
error XARSD7000:   at System.Xml.XmlTextReaderImpl.Read () [0x0008c] in <cd2a19182af54ce694ec155c18cdf0fc>:0
error …
=> [JdkInfo] handle invalid XML from /usr/libexec/java_home

src/Microsoft.Android.Build.BaseTasks/AndroidRidAbiHelper.cs, tests/Microsoft.Android.Build.BaseTasks-Tests/AndroidRidAbiHelperTests.cs
Fixes: https://github.com/xamarin/xamarin-android/issues/5432
Two cases currently do not work in .NET 6:
1) An Android app project includes files such as:
android-arm/libfoo.so
android-arm64/libfoo.so
android-x86/libfoo.so
android-x64/libfoo.so
It would be nice if users could use `$(RuntimeIdentifier)` names
here. We can simply check if the directory name is a RID.
2) A NuGet package includes a native library from a path such as:
packages/sqlitepclraw.lib.e_sqlite3.android/1.1.11/runtimes/android-arm64/native/libe_sqlite3.so
In this case, there is no `%(RuntimeIdentifier)` item metadata on this
native library. So we will have to check if the following is a RID:
Directory.GetParent (lib.ItemSpec).Parent.Name
I implemented these two cases as last resort to the existing logic.
I think this …
=> [BaseTasks] add ABI detection for RIDs

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Mono.Posix.NETStandard is being replaced with the new Mono.Unix
package in Xamarin.Android.  Xamarin.Android imports the
`MSBuildReferences.projitems` file which referenced the older
package.  This commit switches to the new package.
=> Reference the new Mono.Unix nuget

src/Microsoft.Android.Build.BaseTasks/AndroidRidAbiHelper.cs, tests/Microsoft.Android.Build.BaseTasks-Tests/AndroidRidAbiHelperTests.cs
Tests in xamarin-android have started failing with:
libfoo.so : error XA4301: Cannot determine ABI of native library 'libfoo.so'.
Move this file to a directory with a valid Android ABI name such as 'libs/armeabi-v7a/'.
Where the test in question sets `Link=x86\libfoo.so`:
https://github.com/xamarin/xamarin-android/blob/bf63c3d116b38459678cb3aefd2f5826e78c385e/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/XASdkTests.cs#L115
This only fails on macOS and works fine on Windows. I didn't consider
this case in 90d76212.
I've added test cases for `\`, and added a `string.Replace()` that
should solve the problem on macOS.
I added test cases for `null` input as well.
=> [BaseTasks] fix `\`-delimited paths on macOS

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
The new version switched back to `zlib` from `zlib-ng` and increased the
compression level it uses to 9 (from the previous 6)
=> Bump LibZipSharp to 2.0.0-alpha6

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Drops the OS specific MSBuild references to instead
use MSBuild 16.10.0 NuGet packages.  This will
require changes in xamarin/xamarin-android.
=> [Microsoft.Android.Build] Bump to MSBuild 16.10.0

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Context: https://github.com/xamarin/LibZipSharp/commit/fcb9323d9d95b06051f67d8d73ba371a4029722d
Context: https://libzip.org/news/release-1.8.0.html
2.0.0-alpha7 changes:
* bump libzip version to 1.8.0
* add support for ZSTD compression
* properly hide all the native library symbols except for the libzip ones
=> Bump LibZipSharp to 2.0.0-alpha7

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems, src/Microsoft.Android.Build.BaseTasks/Microsoft.Android.Build.BaseTasks.csproj
Let's StrongName our assemblies.
=> StrongName Microsoft.Android.Build.BaseTasks

src/Microsoft.Android.Build.BaseTasks/AsyncTaskExtensions.cs, tests/Microsoft.Android.Build.BaseTasks-Tests/AsyncTaskExtensionsTests.cs
Fixes: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1360410
Context: https://devblogs.microsoft.com/premier-developer/limiting-concurrency-for-faster-and-more-responsive-apps/
A work item came in from VS where AOT compilation is causing
responsiveness issues. The culprit came down to some of the
`TaskScheduler` and `TaskCreationOptions` settings in
`AsyncTaskExtensions`.
@davkean's recommendations are:
> This code needs to do two things:
> 1) It needs to pass `TaskCreationOptions.LongRunning`, so that we
>    don't burn queues meant for short lived tasks.
> 2) It needs to limit how many tasks it starts at once, to avoid CPU
>    contention and reduce the number of threads that we end up
>    burning.
Looking at `AsyncTaskExtensions` usage, it would happen …
=> [BaseTasks] improve Task settings in AsyncTaskExtensions

src/Xamarin.Android.Tools.AndroidSdk/AndroidSdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1314263
Remember `AndroidSdkInfo.DetectAndSetPreferredJavaSdkPathToLatest()`
(commit a4aad186)?  It's supposed to "detect" the latest installed
"preferred" JDK installation location, and set configuration values
so that subsequent `new AndroidSdkInfo()` expressions will use that
JDK location, instead of some other JDK location.
The "preferred" JDK was a JDK that was "known good" for Xamarin.Android
use, i.e. one that Visual Studio installed.  In a4aad186, this was the
`microsoft_dist_openjdk_*` version.
When we (prematurely) removed support for the `microsoft_dist_openjdk_`
build in commits 237642ce and dca30d9d, we updated
`AndroidSdkInfo.DetectAndSetPreferredJavaSdkPathToLatest()` to instead
prefer the [Microsoft OpenJDK][0] …
=> [Xamarin.Android.Tools.AndroidSdk] More Microsoft Dist JDK Support

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs
The code detecting whether an instance of NDK is a 64-bit one assumed
that the GNU binutils paths existed below the toolchains dir and used
them to check whether the 64-bit platform directory exists under them in
order to determine if the NDK is a 64-bit one.  NDK r23, however, will
remove the GNU binutils completely and those paths no longer exist.
Add a check for the `toolchains/llvm/prebuilt/[PLATFORM]` directory
existence before the older check so that detection works correctly for
NDK r23+.
=> [NDK] Properly detect 64-bit NDK

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.Versions.props
Context: https://dl-ssl.google.com/android/repository/repository2-1.xml
Update the preferred Android SDK component versions to the current latest
versions listed in the [Android Repository file][0]:
* `$(AndroidSdkBuildToolsVersion)`/build-tools to 31.0.0
* `$(AndroidCommandLineToolsVersion)`/cmdline-tools to 5.0
* `$(AndroidSdkPlatformToolsVersion)`/platform-tools to 31.0.3
* `$(AndroidSdkPlatformVersion)`/platform to android-31
* `$(AndroidNdkVersion)`/ndk-bundle to 22.1.7171670
Note: there is an NDK r23 package in `ndk;23.0.7599858`, and
xamarin-android supports NDK r23 as of
[xamarin/xamarin-android@f361d997][2], but that is installed into
a *versioned* directory, a'la `$ANDROID_SDK_ROOT/ndk/23.0.7599858`,
which (1) may not be fully supported, and (2) *isn't* supported
by the Android …
=> [Xamarin.Android.Tools.AndroidSdk] Update SDK component for API-31

Directory.Build.targets
Allow a .targets.override file in the parent directory
to customize targets settings for Directory.build.targets.
This is the same change made for androidtools here
https://github.com/xamarin/androidtools/pull/307,
applied to xamarin-android-tools.
=> Allow targets override

Directory.Build.props, src/Microsoft.Android.Build.BaseTasks/Microsoft.Android.Build.BaseTasks.csproj, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
Context: ff73f925a399df523cd89a9b8b49849e63fe0411
Context: 061bcc2eb6e81b2ef7b26ec37315c0c636cf2093
Context: https://github.com/xamarin/XamarinVS/pull/12550
Changing `$(Version)` with every commit is fun and all, but doesn't
solve all problems.  Commit ff73f925 works "nicely" for MSBuild tasks
via [`<UsingTask/>`][0].  It doesn't work as well for "normal"
assembly references in a "normal" AppDomain context, because
assemblies are [normally resolved][1] via "assembly base name", *not*
the full path name including directory.
Thus, given `Example.dll`:
csc /out:Example.dll /r:Path/To/Xamarin.Android.Tools.AndroidSdk.dll
then when `Example.dll` is loaded, it will try to load
`Xamarin.Android.Tools.AndroidSdk` via a `Load-by-name` method, and
will load the first …
=> [build] Allow Assembly "vendorization"

Directory.Build.targets
Allow a .targets.override file in the parent directory
to customize targets settings for Directory.build.targets.
This is the same change made for androidtools here
https://github.com/xamarin/androidtools/pull/307,
applied to xamarin-android-tools.
=> [d17-0] Allow targets override

Directory.Build.props, src/Microsoft.Android.Build.BaseTasks/Microsoft.Android.Build.BaseTasks.csproj, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
Context: ff73f925a399df523cd89a9b8b49849e63fe0411
Context: 061bcc2eb6e81b2ef7b26ec37315c0c636cf2093
Context: https://github.com/xamarin/XamarinVS/pull/12550
Changing `$(Version)` with every commit is fun and all, but doesn't
solve all problems.  Commit ff73f925 works "nicely" for MSBuild tasks
via [`<UsingTask/>`][0].  It doesn't work as well for "normal"
assembly references in a "normal" AppDomain context, because
assemblies are [normally resolved][1] via "assembly base name", *not*
the full path name including directory.
Thus, given `Example.dll`:
csc /out:Example.dll /r:Path/To/Xamarin.Android.Tools.AndroidSdk.dll
then when `Example.dll` is loaded, it will try to load
`Xamarin.Android.Tools.AndroidSdk` via a `Load-by-name` method, and
will load the first …
=> [d17-0][build] Allow Assembly "vendorization" (#136)

src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/JdkInfoTests.cs, tools/ls-jdks/App.cs
Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1397171
Context: https://www.4e00.com/blog/java/2016/12/16/java-command-line-options.html
We have a Watson report of an `InvalidOperationException` being
thrown from `JdkInfo.GetJavaProperties()`:
Xamarin.Android.Tools.AndroidSdk!Xamarin.Android.Tools.JdkInfo
...
clr!IL_Throw
Xamarin.Android.Tools.AndroidSdk!Xamarin.Android.Tools.JdkInfo.__c__DisplayClass46_0._GetJavaProperties_b__0
The dump provides an additional glimmer of information: the
`InvalidOperationException` message text:
Unknown property key for value        (to execute a class)!
`JdkInfo.GetJavaProperties()` only contains one `throw`, for when we
think we're processing a multi-line value, but we don't have a key
for the value encountered.
Which brings us to …
=> [Xamarin.Android.Tools.AndroidSdk] Parse Properties after header

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidSdkInfoTests.cs
Fixes https://work.azdo.io/1433453
Users are reporting the following error when trying to use NDK 22
```
MSB4044: The "MakeBundleNativeCodeExternal" task was not given a value for the required parameter "AndroidNdkDirectory".
```
Earlier in the logs we see this message
```
Skipping NDK in 'C:\ProgramData\Android\android-sdk
dk\22.1.7171670': version 22.1.7171670 is out of the accepted range (major version must be between 16 and 21
```
We need to update the `MaximumCompatibleNDKMajorVersion` to match our new
upper limit.
=> Update MaximumCompatibleNDKMajorVersion to be 23

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
BaRS is conducting an effort to migrate signing in Xamarin pipelines off the [external Groovy pipeline.](https://dev.azure.com/devdiv/DevDiv/_build?definitionId=13878&_a=summary) The goal is to use MicroBuild to handle all signing within the build rather than hand off files for another pipeline to sign. The [Android.SDK.Manager](https://dev.azure.com/devdiv/DevDiv/_build?definitionId=13502&_a=summary) pipeline has been chosen as the first pipeline to migrate. Project files in Android.SDK.Manager reference the [xamarin-android-tools repo](https://github.com/xamarin/android-sdk-installer/blob/684b7e1283706bef2e5c832a64ced0158abe5259/Xamarin.Installer.AndroidSDK.Manager/Xamarin.Installer.AndroidSDK.Manager.csproj#L154) as a submodule and [sign the resource …
=> Adding resource dlls to MicroBuild signing.

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Changes
- Use a different license tag for nuget generation 
- Fix corrupt data when Deleting entries from zip files.
https://github.com/xamarin/LibZipSharp/compare/2.0.0...2.0.2
=> Bump LibZipSharp to 2.0.2

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
We should have used `==` not `!=` when doing the `LibZipSharpVersion`
check.
=> Fix Typo in commit 0dcf7172

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Changes
- Don't rewind the temporary stream on write to the main one
https://github.com/xamarin/LibZipSharp/compare/2.0.2...2.0.3
=> Bump LibZipSharp to 2.0.3

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
Adding condition to GetFilesToSign to only include files if build configuration is Release.
This change is to support signing in the [Android.SDK.Manager](https://dev.azure.com/devdiv/DevDiv/_build?definitionId=13502&_a=summary) build pipeline. A condition was added for the signing ItemGroup to only create it if the `$(Configuration)` is a Release configuration. This is to handle the case where a solution file might build a debug configuration in a real sign build. The debug configuration will ignore the signing ItemGroup.
=> Adding condition to GetFilesToSign

README.md
Context: https://dev.azure.com/xamarin/public/_release?_a=releases&view=mine&definitionId=12
A Release Pipeline has been created to push new versions of
Xamarin.Android.Tools.nupkg for any projecst that depend on it.
=> [ci] Mention new NuGet feed and release

src/Xamarin.Android.Tools.AndroidSdk/AndroidAppManifest.cs, src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Jdks/JdkLocations.MacOS.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs
Context: https://github.com/xamarin/xamarin-android-tools/pull/157
Context: 2d3690e428c8523b3779f84e5c804d1fd3c0d6fe
Commit 2d3690e4 added Nullable Reference Type support to
`Xamarin.Android.Tools.AndroidSdk.dll`.  Unfortunately, it was
largely "surface level", updating *public* API, but not all method
implementations were appropriately updated.
Case in point: if `$HOME/.config/xbuild/monodroid-config.xml`
contains *no* value in `<java-sdk/>`, e.g.
<monodroid>
<android-sdk path="/path/to/android/sdk" />
<java-sdk /> 
</monodroid>
then Visual Studio for Mac may report a first-chance exception
(only reported when debugging Visual Studio for Mac, as the exception
is caught internally):
TODO: exception + stack trace
A major reason to adopt Nullable Reference Types is to *prevent* the …
=> [Xamarin.Android.Tools.AndroidSdk] Attributes can be null!

src/Xamarin.Android.Tools.AndroidSdk/AndroidAppManifest.cs
This change is necessary for enabling adaptive icon support in the Android Manifest property page: https://github.com/xamarin/XamarinVS/pull/12895
It introduces a new attribute `android:roundIcon`.
=> Add support for writing android:roundIcon to Android manifest

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
With the move away from the "sign-from-github-esrp" ("Groovy") pipeline, we need to shift our assembly signing to happen alongside the build itself, which is more secure. Without these changes, we will not be able to push new, signed assemblies from this branch.
=> Backport MicroBuild Signing Changes to d17-0

src/Xamarin.Android.Tools.AndroidSdk/AndroidAppManifest.cs
Context: https://github.com/xamarin/XamarinVS/pull/12895
This change is necessary for enabling adaptive icon support in the Android Manifest property page.
It introduces a new attribute `android:roundIcon`.
Co-authored-by: Jonathan Peppers <jonathan.peppers@microsoft.com>
=> [d17-2] Add support for writing android:roundIcon to Android manifest (#162)

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
With the move away from the "sign-from-github-esrp" ("Groovy") pipeline, we need to shift our assembly signing to happen alongside the build itself, which is more secure. Without these changes, we will not be able to push new, signed assemblies from this branch.
This change cherry-picks the following commits
1. f2cbc6a6ae3d543ae4e9cff0d91087219442e837 (main change)
2. 85ae77fbe946bc3641d25ca8ef4fa3399ad729b7 (added condition)
3. fc3c2ac191a47715bc58e110ef28f38009158416 (bump MicroBuild version)
Test run in the UI Tools pipeline: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6067078&view=results
=> Build Pipeline Fixes (MicroBuild Signing) for d16-11

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Changes
- Add a new more complex unit test
- [ci] Use new EO compliant build pools
- Bump vcpkg to latest version
- Use RuntimeInformation to determine the Processor architecture
https://github.com/xamarin/LibZipSharp/compare/2.0.2...2.0.4
=> Bump LibZipSharp to 2.0.4

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
Context: https://github.com/xamarin/xamarin-android/pull/7073
Context: https://github.com/xamarin/xamarin-android/blob/fdfc4c44ba65fcff9caf809bcf2d1f1a6837b1e3/src/Xamarin.Android.Build.Tasks/Tests/Xamarin.Android.Build.Tests/AndroidDependenciesTests.cs#L19-L50
Trying to figure out how xamarin-android's
`AndroidDependenciesTests.InstallAndroidDependenciesTest()` *passes*;
it creates an empty "SDK" directory, then builds with the
`InstallAndroidDependencies` target, and on main this works,
*even though* it implies that it's creating an `AndroidSdkInfo`
instance with an *empty* SDK directory:
if (Directory.Exists (sdkPath))
Directory.Delete (sdkPath, true);
Directory.CreateDirectory (sdkPath);
// `sdkPath` is not otherwise populated
Yet it *passes* `ValidateAndroidSdkLocation()`: …
=> [Xamarin.Android.Tools.AndroidSdk] Provide more logging

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs
Update `AndroidSdkBase.MaximumCompatibleNDKMajorVersion` to 24, so
that NDK r24 is considered as a valid version.
=> [Xamarin.Android.Tools.AndroidSdk] Permit NDK r24

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.Versions.props, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidSdkInfoTests.cs
Context: https://dl-ssl.google.com/android/repository/repository2-3.xml
Context: https://github.com/xamarin/xamarin-android/commit/e4b3adb389f54bc3d23b38a260093ec3fb53d88e
Update the preferred Android SDK component versions to the current latest
versions listed in the [Android Repository file][0]:
* `$(AndroidSdkBuildToolsVersion)`/build-tools to 32.0.0
* `$(AndroidSdkPlatformToolsVersion)`/platform-tools to 32.0.0
* `$(AndroidSdkPlatformVersion)`/platform to android-32
* `$(AndroidCommandLineToolsVersion)`/cmdline-tools to 7.0
* `$(AndroidNdkVersion)`/NDK to 23.2.8568313
[0]: https://dl-ssl.google.com/android/repository/repository2-3.xml
=> [Xamarin.Android.Tools.AndroidSdk] Update SDK component for API-32

azure-pipelines.yaml
Updates the build to run on the latest macOS and Windows VM images, as
the macOS-10.15 Azure Pipelines agent pool is now deprecated.
=> [ci] Use latest macOS and Windows images

Localize/onelocbuild.yaml
The xamarin-android-tools repo now builds in both the xamarin/public and
devdiv/DevDiv Azure DevOps orgs, and unfortunately CI triggers only work
for [one organization at a time][0]:
"However, if you create pipelines for a single repository in multiple
Azure DevOps organizations, only the first organization's pipelines
can be automatically triggered by GitHub commits or pull requests."
Since the OneLocBuild job can't run against every commit automatically,
the job has been updated to run on a daily schedule so that we can still
get continuous builds.
[0]: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#create-pipelines-in-multiple-azure-devops-organizations-and-projects
=> [ci] Run OneLocBuild on a schedule

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs
When running on NET6 (VSMac installer), SpecialFolder.ApplicationData
returns nothing, resulting in a relative path being used for the config
file. In those cases, check that's the case and fallback to well known
~/.config folder, which is, from what it seems, the default.
=> Fallback to well known config file place

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkBase.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidSdkInfoTests.cs
Context: https://github.com/xamarin/xamarin-android/issues/7233
Update `AndroidSdkBase.MaximumCompatibleNDKMajorVersion` to 25, so
that NDK r25 is considered as a valid version.
=> [Xamarin.Android.Tools.AndroidSdk] Permit NDK r25

Directory.Build.targets, src/Microsoft.Android.Build.BaseTasks/Microsoft.Android.Build.BaseTasks.csproj, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
Context: https://github.com/xamarin/xamarin-android/commit/7b4d4b8c235b22b688db13e59771722da89f37cb
Context: https://github.com/dotnet/sourcelink#githubcom-and-github-enterprise
Context: https://www.hanselman.com/blog/exploring-net-cores-sourcelink-stepping-into-the-source-code-of-nuget-packages-you-dont-own
Add a reference to the [Microsoft.SourceLink.GitHub NuGet package][0]
so that `Microsoft.Android.Build.BaseTasks.pdb` and
`Xamarin.Android.Tools.AndroidSdk.pdb` contain URLs to facilitate
debugging into their corresponding assemblies without needing to
checkout and build the `xamarin-android-tools` repo locally:
% $HOME/.dotnet/tools/sourcelink print-urls src/Microsoft.Android.Build.BaseTasks/bin/Debug/netstandard2.0/Microsoft.Android.Build.BaseTasks.pdb …
=> [ci] Use Microsoft.SourceLink.GitHub

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Update Mono.Unix to a version which correctly p/invokes into `libc` on Unix, 
instead of into `msvcrt`.
Update `LibZipSharp` to a version which includes a fix for a buffer overflow in 
zlib as well as bumps `libzip` native library version to the latest 1.9.2.
The new version of `LibZipSharp` also includes localization changes.
=> Update Mono.Unix and LibZipSharp

src/Xamarin.Android.Tools.AndroidSdk/Jdks/MicrosoftDistJdkLocations.cs, src/Xamarin.Android.Tools.AndroidSdk/OS.cs, src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkUnix.cs
All of the usages of SpecialFolder.Personal should be using UserProfile instead. SpecialFolder Personal is the same value as MyDocuments, both of which will be changed on Unix from `~` to `~/Documents` in .NET 8. See https://github.com/dotnet/runtime/pull/68610.
=> Fix SpecialFolder.Personal usages

Directory.Build.props, azure-pipelines.yaml, src/Microsoft.Android.Build.BaseTasks/Microsoft.Android.Build.BaseTasks.csproj, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj, tests/Microsoft.Android.Build.BaseTasks-Tests/Microsoft.Android.Build.BaseTasks-Tests.csproj, tests/Xamarin.Android.Tools.AndroidSdk-Tests/Xamarin.Android.Tools.AndroidSdk-Tests.csproj, tools/ls-jdks/ls-jdks.csproj
I believe this is a good idea anyway, but this should assist with:
https://github.com/xamarin/xamarin-android/pull/7451
Which is hitting the error:
error NU1102: Unable to find package Microsoft.NETCore.App.Host.osx-x64 with version (= 3.1.31)
.NET Core 3.1.31 is not released yet and is likely on a private feed.
Also pass `6.0.x` to the [`UseDotNet`][0] yaml task.
After these changes, the build failed with:
error MSB3971: The reference assemblies for ".NETFramework,Version=v6.0" were not found. You might be using an older .NET SDK to target .NET 5.0 or higher. Update Visual Studio and/or your .NET SDK.
Mono MSBuild probably can't build .NET 6 projects?
So I fixed various things in the build:
* Use `dotnet build` instead of MSBuild, remove NuGet commands
* No tests were running:
``` …
```
=> Move from `netcoreapp3.1` to `net6.0`

Directory.Build.targets, src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj, tests/Microsoft.Android.Build.BaseTasks-Tests/Microsoft.Android.Build.BaseTasks-Tests.csproj, tests/Xamarin.Android.Tools.AndroidSdk-Tests/Xamarin.Android.Tools.AndroidSdk-Tests.csproj
Context: https://dev.azure.com/xamarin/public/_componentGovernance/115226/alert/3150206?typeId=5477311 Context: https://dev.azure.com/xamarin/public/_componentGovernance/115226/alert/6875331?typeId=5477311 Context: https://github.com/xamarin/java.interop/commit/53182615707bd4181564c0be388d3b09c1d11a20
[Component Governance][0] is a Microsoft internal tool which checks for known security issues in product dependencies.  It is currently reporting a defects in xamarin-android-tools due to use of older `System.Net.Http` packages (]CVE-2018-8292][0]) and older `System.Security.Cryptography.X509Certificates`
packages ([CVE-2017-11770][1]):
> **Location**
>
> * /s/packages/system.net.http/4.1.0/system.net.http.4.1.0.nupkg
> * /s/packages/system.net.http/4.1.0/system.net.http.nuspec
> * …
=> [build] Update NuGet package versions

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Context: https://dev.azure.com/xamarin/public/_componentGovernance/115226/alert/8008980?typeId=5585428&pipelinesTrackingFilter=1
We've receieved an alert about our usage of the 6.0.0 version of
`System.Security.Cryptography.Xml`.  This package is brought in through
the [Microsoft.Build.Tasks.Core][0] package reference.  An explicit
reference to version 6.0.1 of `System.Security.Cryptography.Xml` should
bring in the fix for CVE-2022-34716.
[0]: https://www.nuget.org/packages/Microsoft.Build.Tasks.Core/17.3.2#dependencies-body-tab
=> Add reference to System.Security.Cryptography.Xml

src/Microsoft.Android.Build.BaseTasks/MSBuildExtensions.cs
Context https://github.com/dotnet/maui/issues/11605
If a solution has more than one Android "App" project there is the potential that objects registered using the `RegisterTaskObject` will be reused between the projects.
In most cases this is NOT the desired outcome. There are a few instances where it is safe to share the registered objects between projects. But for most of the time it is specific to that project that is being built. Historically we have probably got away with this because "most" users only have one project.....
So lets update the MSBuildExtensions extension methods to include an additional flags parameter. This will control if the registered object will be "project" scope or "solution" scope. Yes those are terms I just made up :D.
We do this by including the …
=> Add support for Project Specific RegisterTaskObject.

src/Microsoft.Android.Build.BaseTasks/MSBuildExtensions.cs
Context: 76c076fc4876c27e21ea2540e40a27742e7891f1
When attempting to update xamarin/xamarin-android to use 4ea2d5ad, lots of CS0121 errors appeared:
…/src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs(80,18): error CS0121: The call is ambiguous between the following methods or properties: 'MSBuildExtensions.RegisterTaskObjectAssemblyLocal(IBuildEngine4, object, object, RegisteredTaskObjectLifetime, bool)' and 'MSBuildExtensions.RegisterTaskObjectAssemblyLocal(IBuildEngine4, object, object, RegisteredTaskObjectLifetime, bool, RegisterTaskObjectKeyFlags)'
…/src/Xamarin.Android.Build.Tasks/Tasks/FilterAssemblies.cs(87,18): error CS0121: The call is ambiguous between the following methods or properties: 'MSBuildExtensions.RegisterTaskObjectAssemblyLocal(IBuildEngine4, object, object, …
=> Fix CS0121 ambiguity errors.

src/Microsoft.Android.Build.BaseTasks/MSBuildExtensions.cs
Reverts: 47f95ab99f6201d956eecfa1c7b2fd5fa7e43946
Reverts: 76c076fc4876c27e21ea2540e40a27742e7891f1
Context: https://github.com/xamarin/xamarin-android/pull/7685#issuecomment-1381001885
The problem is that we misunderstood
[`IBuildEngine.ProjectFileOfTaskNode`]: we *thought* (hoped?) that it would return `$(MSBuildProjectFullPath)`, the path to the `.csproj` being built.
In actuality it returns `$(MSBuildThisFileFullPath)` for the file containing the Task invocation.  Meaning if e.g.
`Xamarin.Android.Common.targets` contains the Task invocation, then IBuildEngine.ProjectFileOfTaskNode` would be the path to `Xamarin.Android.Common.targets`, *not* the path of the `.csproj`.
This in turn means it doesn't actually solve the problem we had. We will instead need to audit all use of …
=> Revert IBuildEngine.ProjectFileOfTaskNode use.

src/Microsoft.Android.Build.BaseTasks/AndroidAsyncTask.cs, src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs, src/Microsoft.Android.Build.BaseTasks/AndroidToolTask.cs, src/Microsoft.Android.Build.BaseTasks/MSBuildExtensions.cs, tests/Microsoft.Android.Build.BaseTasks-Tests/AndroidToolTaskTests.cs, tests/Microsoft.Android.Build.BaseTasks-Tests/Utilites/MockBuildEngine.cs
Context: dotnet/maui#11605
Context: dotnet/maui#11387 (comment)
Context: http://github.com/xamarin/xamarin-android/commit/8bc7a3e84f95e70fe12790ac31ecd97957771cb2
In dotnet/maui#11605, when `$(AndroidEnableMarshalMethods)`=True (xamarin/xamarin-android@8bc7a3e8), the build may fail if the `.sln` contains more than one Android "App" project.  We tracked this down to "undesired sharing" between project builds; the `obj` provided to [`IBuildEngine4.RegisterTaskObject()`][0] can be visible across project builds.  Consider [`<GeneratePackageManagerJava/>`][1]:
var marshalMethodsState = BuildEngine4.GetRegisteredTaskObjectAssemblyLocal<MarshalMethodsState> (".:!MarshalMethods!:.", RegisteredTaskObjectLifetime.Build);
Further consider a `.sln` with two "App" projects, as the "App" project build …
=> Add new API for generating Project Specific Key for RegisterTaskObject

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Context: https://github.com/xamarin/LibZipSharp/pull/125
The new LibZipSharp version potentially fixes the issue we see 
from time to time on Ci, when an attempt to process a zip 
archive (APK, in our case) ends with an error when trying to 
open the archive.
=> Bump LibZipSharp version

Localize/onelocbuild.yaml
We've been notified that the localization system will create work items
for loc pipelines that do not have regular builds.  To address this, we
can add a weekly build that will always run the OneLocBuild task even if
sources haven't changed.
=> [ci] Add weekly schedule for OneLocBuild

src/Microsoft.Android.Build.BaseTasks/MSBuildExtensions.cs
Adds a copy of `LogWarningForXmlNode` that logs an error instead of a
warning.
=> [Build Tasks] Add LogErrorForXmlNode

src/Xamarin.Android.Tools.AndroidSdk/AndroidAppManifest.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidAppManifestTests.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/Resources/manifest-simplewidget.xml
Context: https://developercommunity.visualstudio.com/t/Cannot-deploy-to-Android-emulators-and-d/10428163
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1863835
Context: https://developer.android.com/guide/components/intents-filters
The [`<activity/>`][0] and related elements within `AndroidManifest.xml` can have multiple [`<intent-filter/>`][1]s specified.  Android does not require that `<intent-filter/>`s be listed in any particular order.
However, Visual Studio *does* care about the order (?!)!
[Activity(Exported = true, Label = "@string/app_name", MainLauncher = true)]
[IntentFilter(
new[] { Android.Content.Intent.ActionView },
Categories = new[] {
Android.Content.Intent.CategoryDefault,
Android.Content.Intent.CategoryBrowsable,
}
)]
[IntentFilter(
new[] { …
=> [Xamarin.Android.Tools.AndroidSdk] Check all <intent-filter/>s

Directory.Build.props
As we consume nightly .NET 8 builds, they sometimes depend on nightly .NET 7 builds.
One error you can run into is:
error NU1102: Unable to find package Microsoft.AspNetCore.App.Ref with version (= 7.0.11)
error NU1102: Unable to find package Microsoft.WindowsDesktop.App.Ref with version (= 7.0.11)
For projects that are not even ASP.NET or Windows desktop apps! To even be able to access these feeds, they would be something like:
<add key="darc-pub-dotnet-aspnetcore-[SHA]" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-aspnetcore-[SHA]/nuget/v3/index.json" />
<add key="darc-pub-dotnet-windowsdesktop-[SHA]" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-windowsdesktop-[SHA]/nuget/v3/index.json" />
We don't currently track these …
=> [build] set `$(DisableTransitiveFrameworkReferenceDownloads)`

src/Xamarin.Android.Tools.AndroidSdk/Jdks/MicrosoftOpenJdkLocations.cs
- VS installer start using a zip payload to install the OpenJDK on %programFiles%/Android/openjdk/jdk-*
=> Update OpenJDK location for OpenJDK17 on windows

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.Versions.props
- Bump platforms-tool to version 34.0.5
- Bump cmdline-tools to version 11.0
- Bump build-tool to version 34.0.0
- Bump NDK to version 26.1.10909125
- Ensures be in sync with Xamarin Android Feed for d17.9
- Enables the creation of pixel 6/7 on VisualStudio Device Manager tool
=> Bumps platforms-tools and cmdline-tools for d17.9

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
In xamarin/xamarin-android, we need to update `MSBuild.StructuredLogger` to be able to move to .NET 9. The `.binlog` file format changed in .NET 9.
It currently fails with:
(Restore target) ->
tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj : error NU1605: Warning As Error: Detected package downgrade: Microsoft.Build.Framework from 17.5.0 to 17.3.2. Reference the package directly from the project to select a different version.
tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj : error NU1605:  MSBuildDeviceIntegration -> MSBuild.StructuredLogger 2.2.100 -> Microsoft.Build.Framework (>= 17.5.0)
tests/MSBuildDeviceIntegration/MSBuildDeviceIntegration.csproj : error NU1605:  MSBuildDeviceIntegration -> Microsoft.Build.Framework (>= 17.3.2) …
=> [build] update $(MSBuildPackageReferenceVersion) to 17.6.3

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Projects that import `MSBuildReferences.projitems` receive a `<PackageReference>` to `Microsoft.Build`.  However, many consumers are `netstandard2.0` and this package does not have that framework, resulting in the following warnings:
```
Warning NU1701 Package 'Microsoft.Build 17.3.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
Warning NU1701 Package 'Microsoft.IO.Redist 6.0.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, …
```
=> [MSBuildReferences.projitems] Allow consumers to opt into `Microsoft.Build` package.

azure-pipelines.yaml
Context: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/25351/APIScan-step-by-step-guide-to-setting-up-a-Pipeline
The ApiScan task has been added to pipeline runs against `main`.  This
task should help us identify related issues earlier, rather than having
to wait for a full scan of VS.
=> [ci] Add API Scan job

azure-pipelines.yaml
Enabling CodeQL on macOS seems to be occasionally causing issues with the Run Tests step:
The argument -p:UseSharedCompilation=false is invalid. Please use the /help option to check the list of valid arguments.
We can avoid this by only enabling CodeQL on the Windows build job.
=> [ci] Only enable CodeQL on Windows build job

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.Versions.props
A `$(JavaSdkVersion)` property has been added to specify the preferred
Java SDK version that will be returned by `<GetAndroidDependencies/>`.
=> [Xamarin.Android.Tools.Versions] Add JavaSdkVersion

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Brings in changes https://github.com/xamarin/LibZipSharp/compare/3.0.0...3.1.1.
A round of library version updates (https://github.com/xamarin/LibZipSharp/commit/ed2ccd5fe34a6fb3327986e6972e7b3850bf1e93) 
[CMake] Add /PROFILE to MSVC link flags (https://github.com/xamarin/LibZipSharp/commit/ca8a64a1d2794dac66ae784a80be2029ccb5fe60)
=> Bump LibZipSharp to 3.1.1

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
For some reason we never check for the ANDROID_HOME environment variable on Windows. This might cause
issues with people using VSCode since we probably
will be using environment variables as a backup when using that IDE.
So lets check those last in the list of paths. This way we will pick up all the other defaults and backups before trying the environment variable.
=> Check for ANDROID_HOME Sdk location on Windows.

src/Microsoft.Android.Build.BaseTasks/AndroidToolTask.cs, src/Microsoft.Android.Build.BaseTasks/UnhandledExceptionLogger.cs, tests/Microsoft.Android.Build.BaseTasks-Tests/AndroidToolTaskTests.cs, tests/Microsoft.Android.Build.BaseTasks-Tests/Microsoft.Android.Build.BaseTasks-Tests.csproj
Context: https://github.com/xamarin/xamarin-android-tools/issues/208
Updates AndroidToolTask to capture all standard output from the tool and log it as an error if the task fails.
=> [AndroidToolTask] Log tool output as error

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Bring in the 3.3.0 LibZipSharp to get the corrupt zip fix.
Bring in the AsyncTask package to get the Telemetry API
=> Bump LibZipSharp and Xamarin.Build.AsyncTask

README.md, azure-pipelines.yaml
The pipeline has been moved to the devdiv org, and in the future can be
split into public/internal pipelines in the dotnet org if necessary.
=> Update pipeline and pipeline info in README.md

src/Microsoft.Android.Build.BaseTasks/Files.cs
Context https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2055618
We know that by default `FileShare` will be `Read` when using a `FileStream`. However lets be totally clear on what we want from this point on, so if there is a problem we know its not us.
=> Be explicit about FileShare mode when using FileStream.

src/Microsoft.Android.Build.BaseTasks/MSBuildReferences.projitems
Changes: https://github.com/dotnet/msbuild/compare/v17.9.5...v17.10.4
Updates $(MSBuildPackageReferenceVersion) to the latest VS 2022 LTS.
This new package version brings in System.Security.Cryptography.Xml
v8.0.0 as a transitive dependency, and as such the explicit v7.0.1
package reference should no longer be necessary.
An explicit package reference has been added for System.Formats.Asn1
v8.0.1 (another transitive dependency of Microsoft.Build) to address
https://github.com/advisories/GHSA-447r-wph3-92pm.
=> Bump to dotnet/msbuild@10fbfbf2

src/Microsoft.Android.Build.BaseTasks/UnhandledExceptionLogger.cs, tests/Microsoft.Android.Build.BaseTasks-Tests/LockCheckTests.cs
Context: https://github.com/dotnet/android/issues/9133
In the above issue, a customer got:
error XARDF7019: System.UnauthorizedAccessException: Access to the path 'GoogleGson.dll' is denied.
at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
at Xamarin.Android.Tasks.RemoveDirFixed.RunTask() in /Users/runner/work/1/s/xamarin-android/src/Xamarin.Android.Build.Tasks/Tasks/RemoveDirFixed.cs:line 54	MauiApp2 (net9.0-android)	C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\34.99.0-preview.6.340\tools\Xamarin.Android.Common.targets
Let's expand upon 11fad9d5 to include …
=> [Microsoft.Android.Build.BaseTasks] report locked files for UnauthorizedAccessException

src/Microsoft.Android.Build.BaseTasks/Files.cs, src/Microsoft.Android.Build.BaseTasks/Microsoft.Android.Build.BaseTasks.csproj, tests/Microsoft.Android.Build.BaseTasks-Tests/FilesTests.cs
Context https://github.com/dotnet/android/issues/9133.
We get collisions between the DTB (or AV) and our main build. This can result in the following error
```
Error (active)	XALNS7019	System.UnauthorizedAccessException: Access to the path 'D:\Projects\MauiApp2\obj\Debug\net9.0-android\android\assets\armeabi-v7a\MauiApp2.dll' is denied.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.File.InternalDelete(String path, Boolean checkHost)
at Microsoft.Android.Build.Tasks.Files.CopyIfChanged(String source, String destination) in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/Files.cs:line 125
at Xamarin.Android.Tasks.MonoAndroidHelper.CopyAssemblyAndSymbols(String source, String destination) in …
```
=> Add a retry attempt when copying files

src/Xamarin.Android.Tools.AndroidSdk/AndroidAppManifest.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidAppManifestTests.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/Resources/manifest-simplewidget.xml, tests/Xamarin.Android.Tools.AndroidSdk-Tests/Xamarin.Android.Tools.AndroidSdk-Tests.csproj
Context https://developer.android.com/guide/topics/manifest/activity-alias-element.
Fixes https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2305723.
So activity-alias allows users to change some settings before calling an activity. 
The idea is that your activity is no longer the main launcher, you still have that entry, but the activity-alias' become the main launchers.
Here is a sample AndroidManifest.xml
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
<application
android:allowBackup="true"
android:icon="@mipmap/appicon"
android:roundIcon="@mipmap/appicon_round"
android:supportsRtl="true">
<activity-alias
android:name=".MainActivityAlias"
android:enabled="true"
android:icon="@mipmap/appicon" …
```
=> Add support to discovering activity-alias activity elements

src/Xamarin.Android.Tools.AndroidSdk/Sdks/AndroidSdkWindows.cs
Context https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2341994
Remove the hardcoded  path to `C:\android-sdk-windows` from the list of backup paths to check when scanning for the android sdk.
=> Remove hardcoded Path

azure-pipelines.yaml, tests/Xamarin.Android.Tools.AndroidSdk-Tests/Xamarin.Android.Tools.AndroidSdk-Tests.csproj
New pipeline: https://dev.azure.com/dnceng-public/public/_build?definitionId=307
=> [ci] Move PR build to dnceng public

src/Xamarin.Android.Tools.AndroidSdk/JdkInfo.cs, src/Xamarin.Android.Tools.AndroidSdk/Jdks/MicrosoftDistJdkLocations.cs, src/Xamarin.Android.Tools.AndroidSdk/OS.cs
OS-specific JDK locators should only be used on the OS that they're intended for.  Remove checks for Linux JDK probe mechanisms such as `/usr/libexec/java_home` and `/usr/lib/jvm/*` from Windows & macOS.
=> [Xamarin.Android.Tools.AndroidSdk] Don't check Linux paths on Windows

Directory.Build.props, azure-pipelines.yaml, src/Microsoft.Android.Build.BaseTasks/Microsoft.Android.Build.BaseTasks.csproj, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj, tests/Microsoft.Android.Build.BaseTasks-Tests/Microsoft.Android.Build.BaseTasks-Tests.csproj, tests/Xamarin.Android.Tools.AndroidSdk-Tests/Xamarin.Android.Tools.AndroidSdk-Tests.csproj, tools/ls-jdks/ls-jdks.csproj
Introduces a `$(DotNetTargetFramework)` property to control the target
framework version used for exe projects, and sets it to the latest
stable .NET version (`net9.0`).
Library and build task projects have been updated to only target
`netstandard2.0`, which is compatible with both .NET Framework and .NET
Core.
=> [build] Update to net9.0 and netstandard2.0

src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj
This library is already trim compatible by pure luck: not using any trimmer unsafe APIs.
Let's add the `net9.0` target framework and opt into the analyzers.
We can also skip `NullableAttributes.cs`, as this file is only needed for `netstandard2.0`.
=> [build] add net9.0 & timmer/aot compatibility

Directory.Build.targets
To be able to distribute things in this repo as a NuGet package, we need to set `$(PackageVersion)` appropriately.
=> [build] set `$(PackageVersion)`

src/Xamarin.Android.Tools.AndroidSdk/AndroidVersion.cs, src/Xamarin.Android.Tools.AndroidSdk/AndroidVersions.cs, src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidVersionTests.cs, tests/Xamarin.Android.Tools.AndroidSdk-Tests/AndroidVersionsTests.cs
Context: https://github.com/dotnet/android/pull/10438
9 months ago in [The First Developer Preview of Android 16][0]:
> **Two Android API releases in 2025**
>
>   * This preview is for the next major release of Android with a
>     planned launch in Q2 of 2025. This release is similar to all of
>     our API releases in the past, where we can have planned
>     behavior changes that are often tied to a targetSdkVersion.
>
>   * …
>
>   * We plan to have another release in Q4 of 2025 which also will
>     include new developer APIs. The Q2 major release will be the
>     only release in 2025 to include planned behavior changes that
>     could affect apps.
The 3rd bullet point is a "25Q4 MINOR SDK RELEASE" , thus introducing the *concept* of a "minor" SDK version, with semantics:
* …
=> [Xamarin.Android.Tools.AndroidSdk] "Minor" SDK version support
